#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $MAMBA_REPO == "mambabot" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0ZhbnRhc3RpY1N1a2hpL01BTUJBLVVTRVJCT1QvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    elif [[ $MAMBA_REPO == "MAMBABOT" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0ZhbnRhc3RpY1N1a2hpL01BTUJBLVVTRVJCT1QvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    elif [[ $MAMBA_REPO =~ $regex ]]
    then
        if [[ $MAMBA_REPO_BRANCH ]]
        then
            echo "${MAMBA_REPO}/archive/${MAMBA_REPO_BRANCH}.zip"
        else
            echo "${MAMBA_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL0ZhbnRhc3RpY1N1a2hpL01BTUJBLVVTRVJCT1QvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    fi
}


_set_bot () {
    local zippath
    zippath="mambabot.zip"
    echo "  Downloading source code ..."
    wget -q $(_get_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    MAMBAPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  Cleaning ..."
    rm -rf "$zippath"
    sleep 5
    cd $MAMBAPATH
    echo "    Starting MambaBot    "
    echo "
                          ╔═╦═╦══╦══╦══╦══╦══╦═╦══╗
                          ║║║║║╔╗║═╦╩║║╣╔╗║╔╗║║╠╗╔╝
                          ║║║║║╠╣║╔╝╔║║╣╠╣║╔╗║║║║║
                          ╚╩═╩╩╝╚╩╝─╚══╩╝╚╩══╩═╝╚╝
    "

    python3 ./setup/updater.py ./requirements.txt requirements.txt
    python3 -m userbot
}

_set_bot
